### ISSUE TITLE
Color settings missing

### ISSUE THREAD

**Issue by polyvertex** [Fuhrmann/keypirinha-theme-builder#1]
Thanks for this awesome tool! :)

I noticed a couple of color settings were missing from both the and the generated output:

* `color_title` is the color of the text located at the left side of the text box that is only displayed once an item has been selected with the `Tab` key. Typically when using the WebSearch package for instance.

* `color_status` is the color of the text in the status bar (which you currently map to `color_faded`)

Note that up to current Keypirinha release (v2.18.2), these two settings are not used ([bug to be fixed](https://github.com/Keypirinha/Keypirinha/issues/316) in next release)

**Comment by Fuhrmann** [comment]
Hey @polyvertex thanks for the heads up! Glad you like it! I'll take a look into it as soon as I can and fix it.

**Comment by polyvertex** [comment]
Also (sorry), there have been GUI-theming changes in v2.19, v2.20 and the v2.21 to come so do not jump on it straight away if you intent to optimize dev time ! I will just come back here to notify :)

**Comment by Fuhrmann** [comment]
Thanks for let me know Jean! I'll wait for an update.

**Comment by Fuhrmann** [comment]
@polyvertex I've added support for the following settings:

color_title
color_status
superjumbo satellite_size
listitem_title_font
font_snormal_size
font_snormal_style
font_normal_size
font_normal_style

The support for control_margin, textbox_padding and listitem_padding using pair values I'll implement in the future, Still trying to figure it out the best way to do it.

Thanks.

**Comment by polyvertex** [comment]
Hey I didn't even have time to post an update here! :)
Thanks!
