### ISSUE TITLE
Improve ease of use. Have to scroll up-down many times.

### ISSUE THREAD

**Issue by bantya** [Fuhrmann/keypirinha-theme-builder#11]
First of all I must say this theme builder is awesome and works perfectly. I have no issue regarding its functionality!

![image](https://user-images.githubusercontent.com/16685565/71798841-7b896780-3079-11ea-8fbe-9ecf78c88404.png)

The problem is with the ease of using this tool. I have fairly common sized laptop screen as you can see above. This is really annoying to scroll down to dial a setting and scroll back up again to see it's effect.

I would really appreciate if:
1. The `General, Layout, Results and Results - Selected` sections to be visible one at a time, that way the inconvenience can be avoided. While one section is visible, others can be hidden (as like tabbed layout)

OR:
2. The results be shown in left of the screen and all the dial-able sections be put in vertical right part of the screen.

I hope you can understand my problem. (I couldn't find any better title for this issue.)

🙏🏼

**Comment by Fuhrmann** [comment]
Hi, thanks for take the time to report this issue. I agree with you, the current layout it's not optimal.

I really like both ideas, but the first one would be easier to implement.

**Comment by bantya** [comment]
That is great!
I love Keypirinha, thus I would really like to have aforementioned functionality to ease-up my life.
Again thanks for this awesome theme builder and I hope to see the changes soon 😉.

🙏

**Comment by Fuhrmann** [comment]
Hi @bantya thanks for the kind words. I developed something I want to share before publish and ask your opinion. Take a look below:

1920 x 1080
![image](https://user-images.githubusercontent.com/1160365/72575385-98f0d980-38a2-11ea-9d06-376704ab1659.png)

1280 X 720
![image](https://user-images.githubusercontent.com/1160365/72575408-b0c85d80-38a2-11ea-9056-25e1304f27be.png)

And here's a gif:

![Peek 16-01-2020 20-58](https://user-images.githubusercontent.com/1160365/72575535-1fa5b680-38a3-11ea-8554-4c3538a1485c.gif)



What do you think? Feel free to suggest anything!

**Comment by Fuhrmann** [comment]
Just an update. I've added a logo, a favicon and a `Random theme` button:

![image](https://user-images.githubusercontent.com/1160365/72675857-e6b34080-3a60-11ea-8697-10d983e151c8.png)


---

![demo](https://user-images.githubusercontent.com/1160365/72675865-fa5ea700-3a60-11ea-83d9-c6ae29fec7b8.gif)

**Comment by Fuhrmann** [comment]
The changes are now online! Please let me know if  you have any problems.

**Comment by bantya** [comment]
Sorry for not being able to reply soon 😞.

The changes are looking promising, it works perfectly! But I found a thing or two that are offsetting.

1. 
**Issue:** The color-pickers cause page dimensions to change when invoked from color fields near right and bottom edges, and resizes the dimensions once the color-picker is hidden. We have to scroll vertical-horizontal to reach to the picker.
This jumpy behavior is unexpected. 😖

![SGKyP1lGES](https://user-images.githubusercontent.com/16685565/73011027-8265f780-3e39-11ea-935c-71f5247dc20a.gif)

**Suggestion:** The color-pickers when invoked *must* respect the page boundaries be placed in visible page area.

2. 

**Issue:** When `Random Theme` is selected, the pre-selected `Preset` stays the same (if changed already) but the result switches to `JumboLayout`. To change the result to desired layout, first we have to select any layout option other than selected and then change again to desired layout.

![tTHxPJy6xc](https://user-images.githubusercontent.com/16685565/73011919-4338a600-3e3b-11ea-9a5c-240e4b397380.gif)

**Suggestion:** Upon selecting the `Random Theme`, the `Preset` (the option!) *must* change to `JumboLayout` so that we can actually start with clean slate.

Thanks again for this tool, thus you saved millions of man-hours! 😁

PS: The icon looks simplistic and to-the-point btw.

🙏🏼

**Comment by Fuhrmann** [comment]
Hi! No problem! Thanks for the feedback. I'll fix the problems you pointed and when done I'll let you know!

**Comment by Fuhrmann** [comment]
I`ve just updated the theme creator with the fixes for the bugs you pointed out. Let me know if you have any more problems!

**Comment by bantya** [comment]
I'll check this afternoon (in India)..
Thanks again!

🙏

**Comment by bantya** [comment]
Just checked it. It's all right now. Works flawlessly (until I find anything 😉).

Thanks again for your time. 👍🏼

🙏🏼

**Comment by Fuhrmann** [comment]
Nice!😁

Thanks for testing and helping this project improve!
